server:
  port: 8099
spring:
  application:
    name: lagou-service-autodeliver
  cloud:
    nacos:
      discovery:
        # 集群中各个节点都配置在这里（域名-VIP-绑定映射到各个实例的地址信息）
        server-addr: 127.0.0.1:8848, 127.0.0.1:8858, 127.0.0.1:8868
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080 # sentinel dashboard/console 地址
        port: 8719 # sentinel 会在该端口启动 http server，那么这样的话，控制台定义的一些限流等规则才能发动传递过来，
                   # 如果8719端口被占用，那么会依次+1
      # Sentinel Nacos数据源配置，Nacos中的规则会⾃动同步到sentinel控制台的流控规则中
      datasource:
        # 此处的flow为⾃定义数据源名
        flow: # 流控规则
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            data-id: ${spring.application.name}-flow-rules
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow # 类型来⾃RuleType类
        # 自定义的降级规则数据源名称
        degrade:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            data-id: ${spring.application.name}-degrade-rules
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: degrade # 类型来⾃RuleType类
  main:
    allow-bean-definition-overriding: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  # 暴露健康检查接口细节
  endpoint:
    health:
      show-details: always
dubbo:
  registry:
    # 挂载到Spring Cloud注册中心
    address: spring-cloud://localhost
  cloud:
    # 订阅服务提供⽅的应⽤列表，订阅多个服务提供者使⽤ "," 连接
    subscribed-services: lagou-service-resume
