#eureka server服务接口
server:
  port: 8762
spring:
  application:
    name: lagou-cloud-eureka-server # 应用名称，应用名称会在Eureka中作为服务名称

# eureka 客户端配置 (和Server交互)，Eureka Server其实也是一个Client
eureka:
  instance:
    hostname: LagouCloudEurekaServerB
  client:
    service-url: # 配置客户端所交互的Eureka Server的地址
      defaultZone: http://LagouCloudEurekaServerA:8761/eureka
    register-with-eureka: true # 集群模式下改成true
    fetch-registry: true # 集群模式下改成true

